# {{BUSINESS}} · AI Employee Pack

Five AI employees for {{BUSINESS}} ({{INDUSTRY}}, {{LOCATION}}), generated by
PHX Growth from `client.json`. Same crew architecture that runs Eagle Landscaping.

| Employee | Role | Invoke |
|---|---|---|
| {{AGENT_SALES}} | Sales Closer — no lead goes cold | `@{{SLUG}}-sales-closer` |
| {{AGENT_DISPATCH}} | Dispatch & Scheduling | `@{{SLUG}}-dispatch` |
| {{AGENT_BILLING}} | Billing & QuickBooks | `@{{SLUG}}-billing` |
| {{AGENT_CARE}} | Client Care & Retention | `@{{SLUG}}-client-care` |
| {{AGENT_GROWTH}} | Growth & Marketing | `@{{SLUG}}-growth` |

## Install (2 minutes)

1. Copy the `.claude/` folder into the client's working directory (any folder
   where Claude Code runs — a repo, or an empty ops folder):

   ```bash
   cp -R .claude /path/to/client-workspace/
   ```

2. Open Claude Code in that directory. The five agents are live — invoke any of
   them by name, e.g. `@{{SLUG}}-sales-closer work the leads`.

3. Connect the pipes (all optional — agents draft-and-report until connected):
   - **Zapier MCP** — Slack alerts, Gmail sends, Google Sheets log, QuickBooks.
   - **Google Calendar / Sheets** — jobs and leads source of truth.

## Go 24/7 (optional)

Pair with **Pixel Automation System** (`client.json` here is compatible with its
`client.config.json`) for the always-on webhook engine: instant quotes, follow-up
sequencer, review harvester, marketing autopilot, and the Monday owner report.

## Regenerate

Edit `client.json`, then from the PHX-Growth repo:

```bash
npm run new:client -- clients/{{SLUG}}/client.json
```
