// ─── PIXEL PILOT · DAILY BOARD MEETING ───────────────────────────────────────
// Three AI executives hold a stand-up board meeting each morning and leave behind
// persisted minutes. The engine is dependency-free: when ANTHROPIC_API_KEY is set
// each member's brief is generated by the Anthropic Messages API (plain fetch, no
// SDK); otherwise a believable templated brief stands in — same "simulation when
// creds absent" philosophy as the rest of the platform. Metrics are pulled from
// the KV store when present and simulated deterministically from the date when not,
// so the same day always reads the same numbers.

import { get, saveBoardMeeting, getBoardMeeting, listBoardMeetings } from './store';

// Re-export the persistence helpers so callers can reach them from the barrel too.
export { saveBoardMeeting, getBoardMeeting, listBoardMeetings };

// A fast model on purpose — three short briefs, not long-horizon reasoning.
const BOARD_MODEL = 'claude-haiku-4-5-20251001';

// ── The board ────────────────────────────────────────────────────────────────

export interface BoardMember {
  readonly id: string;
  readonly name: string;
  readonly role: string;
  /** Short description of what this seat owns. */
  readonly mandate: string;
  /** The persona used to steer LLM brief generation. */
  readonly systemPrompt: string;
}

export const BOARD_MEMBERS: BoardMember[] = [
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Chief Growth Officer',
    mandate: 'Media buying, budget allocation, ROAS, and scale-or-kill calls.',
    systemPrompt:
      "You are Atlas, Chief Growth Officer of an autonomous media-buying platform. You own media buying, budget allocation, ROAS, and scale-or-kill decisions across Meta, Google and TikTok. Speak like a sharp, numbers-first growth operator. Given the morning metrics, write a tight board brief (3-5 sentences) covering how spend is pacing, where marginal ROAS is best, and one concrete scale-or-kill recommendation. No preamble, no headings — just the brief.",
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Chief Creative Officer',
    mandate: 'Ad creative performance, creative refresh, and hooks / angles.',
    systemPrompt:
      "You are Nova, Chief Creative Officer of an autonomous media-buying platform. You own ad creative performance, creative refresh cadence, and hooks/angles. Speak like a decisive creative lead who reads the metrics. Given the morning numbers, write a tight board brief (3-5 sentences) on creative fatigue signals, which hooks/angles to double down on, and what to refresh today. No preamble, no headings — just the brief.",
  },
  {
    id: 'ledger',
    name: 'Ledger',
    role: 'Chief Revenue Officer',
    mandate: 'Pipeline, revenue, CAC/LTV, cash, and the forecast.',
    systemPrompt:
      "You are Ledger, Chief Revenue Officer of an autonomous media-buying platform. You own pipeline, revenue, CAC/LTV, cash position, and the forecast. Speak like a rigorous, plain-spoken finance chief. Given the morning metrics, write a tight board brief (3-5 sentences) on revenue vs. spend, CAC/LTV health, cash runway, and the near-term forecast. No preamble, no headings — just the brief.",
  },
];

export function getBoardMember(id: string): BoardMember | undefined {
  return BOARD_MEMBERS.find((m) => m.id === id);
}

// ── The minutes ────────────────────────────────────────────────────────────────

export interface BoardBrief {
  readonly memberId: string;
  readonly name: string;
  readonly role: string;
  readonly brief: string;
}

export interface ActionItem {
  readonly owner: string;
  readonly task: string;
}

export interface BoardMeeting {
  readonly id: string;
  /** YYYY-MM-DD (the meeting day, UTC). */
  readonly date: string;
  /** ISO timestamp of when the minutes were produced. */
  readonly createdAt: string;
  readonly agenda: string[];
  readonly briefs: BoardBrief[];
  readonly decisions: string[];
  readonly actionItems: ActionItem[];
  readonly summary: string;
}

// ── Metrics (real when stored, simulated deterministically otherwise) ──────────

export interface BoardMetrics {
  readonly spend: number;
  readonly roas: number;
  readonly revenue: number;
  readonly pipeline: number;
  readonly cac: number;
  readonly ltv: number;
}

/** Deterministic 0..1 pseudo-random seeded from a string, so a date is stable. */
function seededUnit(seed: string, salt: number): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 16777619);
  }
  // xorshift finish
  h ^= h << 13;
  h ^= h >>> 17;
  h ^= h << 5;
  return ((h >>> 0) % 100000) / 100000;
}

function round(n: number, dp = 0): number {
  const f = 10 ** dp;
  return Math.round(n * f) / f;
}

function simulatedMetrics(date: string): BoardMetrics {
  const spend = round(8000 + seededUnit(date, 1) * 12000, 0);
  const roas = round(2.1 + seededUnit(date, 2) * 2.4, 2);
  const revenue = round(spend * roas, 0);
  const pipeline = round(revenue * (1.4 + seededUnit(date, 3) * 1.2), 0);
  const cac = round(28 + seededUnit(date, 4) * 44, 0);
  const ltv = round(cac * (3 + seededUnit(date, 5) * 4), 0);
  return { spend, roas, revenue, pipeline, cac, ltv };
}

/** Pull whatever platform metrics the store holds; simulate the rest. */
async function loadMetrics(date: string): Promise<BoardMetrics> {
  const base = simulatedMetrics(date);
  try {
    const stored = await get<Partial<BoardMetrics>>('pixel-pilot:metrics');
    if (stored && typeof stored === 'object') {
      return { ...base, ...stored };
    }
  } catch {
    // fall through to simulation
  }
  return base;
}

// ── Brief generation ─────────────────────────────────────────────────────────

function money(n: number): string {
  return `$${n.toLocaleString('en-US')}`;
}

function metricsContext(m: BoardMetrics, date: string): string {
  return [
    `Morning metrics for ${date}:`,
    `- Ad spend (trailing 24h): ${money(m.spend)}`,
    `- Blended ROAS: ${m.roas.toFixed(2)}x`,
    `- Attributed revenue: ${money(m.revenue)}`,
    `- Open pipeline: ${money(m.pipeline)}`,
    `- CAC: ${money(m.cac)}`,
    `- LTV: ${money(m.ltv)} (LTV:CAC ${round(m.ltv / m.cac, 1)}:1)`,
  ].join('\n');
}

/** Ask Anthropic for a brief; return null on any error or missing key. */
async function llmBrief(member: BoardMember, context: string): Promise<string | null> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model: BOARD_MODEL,
        max_tokens: 400,
        system: member.systemPrompt,
        messages: [{ role: 'user', content: context }],
      }),
    });
    if (!res.ok) return null;
    const data = (await res.json()) as { content?: { type: string; text?: string }[] };
    const text = (data.content ?? [])
      .filter((b) => b.type === 'text' && b.text)
      .map((b) => b.text)
      .join('')
      .trim();
    return text || null;
  } catch {
    return null;
  }
}

/** Deterministic templated brief — the dry-run stand-in when no LLM is available. */
function templatedBrief(member: BoardMember, m: BoardMetrics): string {
  const scale = m.roas >= 3;
  switch (member.id) {
    case 'atlas':
      return (
        `Spend is pacing at ${money(m.spend)} against a blended ${m.roas.toFixed(2)}x ROAS. ` +
        `Meta is carrying the best marginal return this morning, with Google steady and TikTok the weakest tail. ` +
        (scale
          ? `Recommendation: scale the top two ad sets +${round(15 + m.roas * 3)}% and let the profit signal keep pulling budget to the leaders.`
          : `Recommendation: hold total spend flat, kill the bottom-quartile ad sets, and reallocate that ${money(round(m.spend * 0.12))} into the proven winners before scaling.`)
      );
    case 'nova':
      return (
        `Creative is the lever today. The hero hook is showing early fatigue as frequency climbs, and CTR on the oldest angle is decaying. ` +
        `The problem-agitate hook and the founder-POV angle are still converting well and deserve more budget. ` +
        `Refreshing three variants off the winning genome now — new opener, same proven arc — to stay ahead of fatigue before it drags ${m.roas.toFixed(2)}x ROAS down.`
      );
    case 'ledger':
      return (
        `Revenue of ${money(m.revenue)} on ${money(m.spend)} spend keeps us comfortably profit-positive. ` +
        `CAC sits at ${money(m.cac)} against ${money(m.ltv)} LTV — a healthy ${round(m.ltv / m.cac, 1)}:1 ratio that supports leaning in. ` +
        `Open pipeline is ${money(m.pipeline)} and cash is ample. ` +
        `Forecast: if today's pace holds we clear ${money(round(m.revenue * 30))} for the month; the main watch item is keeping CAC under ${money(round(m.cac * 1.2))} as we scale.`
      );
    default:
      return `${member.name} reviewed the numbers and has no blockers to raise.`;
  }
}

async function buildBrief(member: BoardMember, context: string, m: BoardMetrics): Promise<string> {
  const live = await llmBrief(member, context);
  return live ?? templatedBrief(member, m);
}

// ── Assembly ───────────────────────────────────────────────────────────────────

function assembleAgenda(date: string, m: BoardMetrics): string[] {
  return [
    `Overnight performance review — ${money(m.spend)} spent at ${m.roas.toFixed(2)}x ROAS on ${date}.`,
    'Atlas: budget allocation & scale-or-kill decisions.',
    'Nova: creative fatigue & refresh plan.',
    'Ledger: revenue, CAC/LTV and the forecast.',
    'Confirm today’s action items and owners.',
  ];
}

function assembleDecisions(m: BoardMetrics): string[] {
  const scale = m.roas >= 3;
  return [
    scale
      ? `Scale the winning ad sets (ROAS ${m.roas.toFixed(2)}x clears the bar) and let profit pull budget to the leaders.`
      : `Hold total spend and reallocate from the bottom quartile into proven winners before any scale-up.`,
    'Ship three refreshed creative variants off the winning genome today.',
    `Maintain the ${round(m.ltv / m.cac, 1)}:1 LTV:CAC guardrail — pause any channel that pushes CAC past ${money(round(m.cac * 1.2))}.`,
  ];
}

function assembleActionItems(): ActionItem[] {
  return [
    { owner: 'Atlas', task: 'Rebalance budgets to the top ad sets and cut the bottom-quartile spenders.' },
    { owner: 'Nova', task: 'Render and publish three refreshed creative variants before noon.' },
    { owner: 'Ledger', task: 'Update the monthly forecast and flag any CAC drift to the war room.' },
  ];
}

function assembleSummary(date: string, m: BoardMetrics): string {
  return (
    `On ${date} the board reviewed ${money(m.spend)} in spend returning ${money(m.revenue)} at ${m.roas.toFixed(2)}x ROAS. ` +
    `Atlas is steering budget to the leaders, Nova is refreshing creative ahead of fatigue, and Ledger confirms a healthy ` +
    `${round(m.ltv / m.cac, 1)}:1 LTV:CAC with ${money(m.pipeline)} of open pipeline. The platform stays hands-off and profit-positive.`
  );
}

// ── Public entry point ─────────────────────────────────────────────────────────

export interface RunBoardMeetingOptions {
  /** Override the meeting date (YYYY-MM-DD). Defaults to today, UTC. */
  date?: string;
}

/** Convert a Date to a YYYY-MM-DD string in UTC. */
export function toDateKey(d: Date = new Date()): string {
  return d.toISOString().slice(0, 10);
}

/** Run the daily board meeting, persist the minutes, and return them. */
export async function runBoardMeeting(opts: RunBoardMeetingOptions = {}): Promise<BoardMeeting> {
  const date = opts.date ?? toDateKey();
  const metrics = await loadMetrics(date);
  const context = metricsContext(metrics, date);

  const briefs: BoardBrief[] = await Promise.all(
    BOARD_MEMBERS.map(async (member) => ({
      memberId: member.id,
      name: member.name,
      role: member.role,
      brief: await buildBrief(member, context, metrics),
    }))
  );

  const meeting: BoardMeeting = {
    id: `board_${date}`,
    date,
    createdAt: new Date().toISOString(),
    agenda: assembleAgenda(date, metrics),
    briefs,
    decisions: assembleDecisions(metrics),
    actionItems: assembleActionItems(),
    summary: assembleSummary(date, metrics),
  };

  await saveBoardMeeting(meeting);
  return meeting;
}
